services:
  auth:
    build:
      context: bingo-auth/.
      target: final
    ports:
      - 8081:8081
    environment:
      - DB_CONN=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}?sslmode=disable
      - JWT_KEY=${JWT_KEY}
    depends_on:
      db:
        condition: service_healthy
  
  api:
    image: daronwastaken/bingo-api:${DOCKER_IMAGE_TAG}
    build:
      context: bingo-api/.
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ConnectionStrings:DefaultConnection=Host=db;Port=5432;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Database=${POSTGRES_DB};
      - Jwt:Key=${JWT_KEY}
  
  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - go-auth-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 5432
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  bingo-db-data: